# Generated by Django 4.2.7 on 2023-12-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sale',
            field=models.IntegerField(null=True),
        ),
    ]
