# Generated by Django 4.2.7 on 2023-12-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='sale',
        ),
    ]
