# Generated by Django 4.2.7 on 2023-12-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footerlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='footerLogo',
        ),
    ]
