# Generated by Django 4.2.7 on 2023-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
